### ISSUE TITLE
Migrate to GitHub actions

### ISSUE THREAD

**Issue by beta-ziliani** [crystal-lang/crystal-env#5]
Now it's pointing at bintray.

**Comment by straight-shoota** [comment]
Sorry, what do you mean? I don't think `distribution-scripts` is used in this repo.

**Comment by straight-shoota** [comment]
Ah, I see you mean the travis-CI setup. https://travis-ci.com/github/crystal-lang/crystal-env/builds/226263113

Technically, this should fix itself when https://github.com/travis-ci/travis-build/pull/1987 gets merged. But there seems little activity over there.

However we should probably migrate all Crystal projects to GitHub Actions to consolidate on a single CI provider.
Travis doesn't seem to look at a bright future, with travis-ci.org being shut down.

**Comment by beta-ziliani** [comment]
that's a better name :-)
